#standardSQL

--SELECT * FROM `**REDACTED**.medication.INFORMATION_SCHEMA.VIEWS`;
DECLARE TABLENAMES ARRAY<STRING>;
DECLARE VIEWNAMES  ARRAY<STRING>;
DECLARE i INT64 DEFAULT 0;
SET TABLENAMES = ARRAY(SELECT table_name FROM `**REDACTED**.medication.INFORMATION_SCHEMA.TABLES` WHERE table_type = "BASE TABLE");
SET VIEWNAMES  = ARRAY(SELECT table_name FROM `**REDACTED**.medication.INFORMATION_SCHEMA.TABLES` WHERE table_type = "VIEW");

LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(TABLENAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP TABLE `**REDACTED**.medication.", TABLENAMES[ORDINAL(i)], "`;");
END LOOP;

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(VIEWNAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP VIEW `**REDACTED**.medication.", VIEWNAMES[ORDINAL(i)], "`;");
END LOOP;
