#standardSQL

-- Drop all tables, views, and routines from the timecourse dataset and the sa
-- dataset
DECLARE TABLENAMES   ARRAY<STRING>;
DECLARE VIEWNAMES    ARRAY<STRING>;
DECLARE ROUTINENAMES ARRAY<STRING>;
DECLARE i INT64 DEFAULT 0;

SET TABLENAMES   = ARRAY(SELECT table_name FROM `**REDACTED**.timecourse.INFORMATION_SCHEMA.TABLES` WHERE table_type = "BASE TABLE" AND table_name NOT LIKE 'timecourse%');
SET VIEWNAMES    = ARRAY(SELECT table_name FROM `**REDACTED**.timecourse.INFORMATION_SCHEMA.TABLES` WHERE table_type = "VIEW");
SET ROUTINENAMES = ARRAY(SELECT routine_name FROM `**REDACTED**.timecourse.INFORMATION_SCHEMA.ROUTINES`);

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(TABLENAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP TABLE `**REDACTED**.timecourse.", TABLENAMES[ORDINAL(i)], "`;");
END LOOP;

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(VIEWNAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP VIEW `**REDACTED**.timecourse.", VIEWNAMES[ORDINAL(i)], "`;");
END LOOP;

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(ROUTINENAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP PROCEDURE `**REDACTED**.timecourse.", ROUTINENAMES[ORDINAL(i)], "`;");
END LOOP;



SET TABLENAMES   = ARRAY(SELECT table_name FROM `**REDACTED**.sa.INFORMATION_SCHEMA.TABLES` WHERE table_type = "BASE TABLE" AND table_name NOT LIKE 'timecourse%');
SET VIEWNAMES    = ARRAY(SELECT table_name FROM `**REDACTED**.sa.INFORMATION_SCHEMA.TABLES` WHERE table_type = "VIEW");
SET ROUTINENAMES = ARRAY(SELECT routine_name FROM `**REDACTED**.sa.INFORMATION_SCHEMA.ROUTINES`);

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(TABLENAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP TABLE `**REDACTED**.sa.", TABLENAMES[ORDINAL(i)], "`;");
END LOOP;

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(VIEWNAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP VIEW `**REDACTED**.sa.", VIEWNAMES[ORDINAL(i)], "`;");
END LOOP;

SET i = 0;
LOOP
  SET i = i + 1;
  IF i > ARRAY_LENGTH(ROUTINENAMES) THEN LEAVE;
  END IF;
  EXECUTE IMMEDIATE CONCAT("DROP PROCEDURE `**REDACTED**.sa.", ROUTINENAMES[ORDINAL(i)], "`;");
END LOOP;
